# Generated by Django 3.0.4 on 2020-04-21 21:21

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='users')),
                ('gender', models.CharField(blank=True, max_length=64)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('education', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='matches.Education')),
                ('friendslist', models.ManyToManyField(blank=True, related_name='_user_info_friendslist_+', to='matches.User_info')),
                ('hobbies', models.ManyToManyField(blank=True, related_name='members', to='matches.Hobby')),
            ],
        ),
    ]
