# Generated by Django 3.0.4 on 2020-04-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20200422_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='matches.Education'),
        ),
    ]
